import { useEffect, useRef, useState } from "react";
import { Turnstile, type TurnstileInstance } from "@marsidev/react-turnstile";
import type { User } from "@supabase/supabase-js";
import { Loader2 } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "./ui/dialog";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Label } from "./ui/label";
import { sendEmailCode, sendLegacyUsernameCode, usernameFromEmail, validateEmail, verifyEmailCode, type AuthKind } from "../lib/authApi";

const TURNSTILE_SITE_KEY = (import.meta.env.VITE_TURNSTILE_SITE_KEY as string | undefined) || "";
const PRIMARY = "h-11 w-full bg-black text-base font-medium text-[#fffbea] hover:bg-gray-800";
type View = "email" | "code" | "legacy";

export function AuthDialog({ open, onOpenChange, onAuthenticated, initialUsername }: { open: boolean; onOpenChange: (open: boolean) => void; onAuthenticated: (kind: AuthKind, user: User) => Promise<void>; initialUsername?: string }) {
  const [view, setView] = useState<View>("email"); const [email, setEmail] = useState(""); const [code, setCode] = useState(""); const [legacyName, setLegacyName] = useState("");
  const [error, setError] = useState<string | null>(null); const [info, setInfo] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [syncing, setSyncing] = useState(false); const [captchaToken, setCaptchaToken] = useState<string | null>(null);
  const turnstileRef = useRef<TurnstileInstance | null>(null);
  useEffect(() => { if (!open) return; setView("email"); setEmail(""); setCode(""); setLegacyName(""); setError(null); setInfo(null); setBusy(false); setSyncing(false); setCaptchaToken(null); }, [open]);
  const captchaRequired = !!TURNSTILE_SITE_KEY; const resetCaptcha = () => { setCaptchaToken(null); turnstileRef.current?.reset(); };
  const captcha = captchaRequired ? <div className="flex min-h-[65px] justify-center"><Turnstile ref={turnstileRef} siteKey={TURNSTILE_SITE_KEY} onSuccess={setCaptchaToken} onExpire={() => setCaptchaToken(null)} onError={() => setCaptchaToken(null)} options={{ theme: "light", size: "flexible" }} /></div> : null;
  const send = async (event: React.FormEvent) => { event.preventDefault(); const validation = validateEmail(email); const username = usernameFromEmail(email); if (validation) { setError(validation); return; } if (!username) { setError("Use an email with a name before the @ sign."); return; } setBusy(true); setError(null); try { const result = await sendEmailCode({ email, username, upgradingGuest: !!initialUsername, captchaToken: captchaToken ?? undefined }); if (!result.ok) { setError(result.message); return; } setView("code"); setInfo(`We sent a 6-digit code to ${email.trim()}.`); } finally { setBusy(false); resetCaptcha(); } };
  const sendLegacy = async (event: React.FormEvent) => { event.preventDefault(); if (!legacyName.trim()) { setError("Enter the username you used before."); return; } setBusy(true); setError(null); try { const result = await sendLegacyUsernameCode({ username: legacyName, captchaToken: captchaToken ?? undefined }); if (!result.ok) { setError(result.message); return; } setEmail(result.email); setView("code"); setInfo("We sent a 6-digit code to the email linked to that account."); } finally { setBusy(false); resetCaptcha(); } };
  const verify = async (event: React.FormEvent) => { event.preventDefault(); if (!/^\d{6}$/.test(code.trim())) { setError("Enter the 6-digit code from your email."); return; } setBusy(true); setError(null); try { const result = await verifyEmailCode({ email, code }); if (!result.ok) { setError(result.message); return; } setSyncing(true); await onAuthenticated("signup", result.user); } finally { setSyncing(false); setBusy(false); } };
  return <Dialog open={open} onOpenChange={next => !syncing && onOpenChange(next)}><DialogContent className="sm:max-w-sm">{syncing ? <div className="flex flex-col items-center gap-3 py-8 text-center"><Loader2 className="size-6 animate-spin text-muted-foreground" /><DialogTitle className="text-base">Saving your account…</DialogTitle></div> : <>{view === "email" && <><DialogHeader><DialogTitle>Save your play</DialogTitle><DialogDescription>Use your email to save progress, unlock the archive, and continue on any device.</DialogDescription></DialogHeader><form onSubmit={send} className="mt-4 flex flex-col gap-4"><div className="flex flex-col gap-1.5"><Label htmlFor="account-email">Email</Label><Input id="account-email" type="email" autoComplete="email" value={email} onChange={e => setEmail(e.target.value)} autoFocus disabled={busy} /><p className="text-xs text-muted-foreground">Your leaderboard name is the part before @.</p></div>{captcha}{error && <p className="text-sm text-red-700">{error}</p>}<Button type="submit" className={PRIMARY} disabled={busy || (captchaRequired && !captchaToken)}>{busy ? "Sending code…" : "Email me a code"}</Button><Button type="button" variant="link" className="h-auto p-0" onClick={() => { setView("legacy"); setError(null); }}>I played before but don’t know my email</Button></form></>}{view === "legacy" && <><DialogHeader><DialogTitle>Find your earlier account</DialogTitle><DialogDescription>Enter the username you used before. We’ll send a code to its saved email.</DialogDescription></DialogHeader><form onSubmit={sendLegacy} className="mt-4 flex flex-col gap-4"><div className="flex flex-col gap-1.5"><Label htmlFor="legacy-username">Earlier username</Label><Input id="legacy-username" value={legacyName} onChange={e => setLegacyName(e.target.value)} autoFocus disabled={busy} /></div>{captcha}{error && <p className="text-sm text-red-700">{error}</p>}<Button type="submit" className={PRIMARY} disabled={busy || (captchaRequired && !captchaToken)}>{busy ? "Sending code…" : "Email me a code"}</Button><Button type="button" variant="ghost" onClick={() => { setView("email"); setError(null); }}>Back</Button></form></>}{view === "code" && <><DialogHeader><DialogTitle>Enter your code</DialogTitle><DialogDescription>{info}</DialogDescription></DialogHeader><form onSubmit={verify} className="mt-4 flex flex-col gap-4"><div className="flex flex-col gap-1.5"><Label htmlFor="email-code">6-digit code</Label><Input id="email-code" inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={e => setCode(e.target.value.replace(/\D/g, ""))} autoFocus disabled={busy} /></div>{error && <p className="text-sm text-red-700">{error}</p>}<Button type="submit" className={PRIMARY} disabled={busy}>{busy ? "Checking code…" : "Continue"}</Button><Button type="button" variant="link" onClick={() => { setView("email"); setCode(""); setError(null); }}>Use a different email</Button></form></>}</>}</DialogContent></Dialog>;
}
